CREATE DATABASE PetTakip;
GO

USE PetTakip;
GO

CREATE TABLE Pet (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    Breed NVARCHAR(100) NOT NULL,
    Age INT NOT NULL,
    Gender NVARCHAR(10) NOT NULL,
    Weight DECIMAL(5,2) NOT NULL,
    Color NVARCHAR(50) NOT NULL,
    BirthDate DATE NOT NULL,
    Owner NVARCHAR(100) NOT NULL,
    Microchip NVARCHAR(100) NOT NULL
);
